### ISSUE TITLE
HDMI 2.1 FRL additions

### ISSUE THREAD

**Issue by tim292stro** [tomverbeure/tomverbeure.github.io#7]
Hey, I found your VESA calculator (video_timings_calculator.html) from a quick Google search - I wanted to make a recommendation to add some complexity to your HDMI2.1 numbers.

HDMI 2.1 FRL is a bit more complicated than just one rate.  There's:
3Gx3-lanes  <-- these modes allow for compatibility with older TMDS-type HDMI cables
6Gx3-lanes  <-- these modes allow for compatibility with older TMDS-type HDMI cables
6Gx4-lanes
8Gx4-lanes
10Gx4-lanes
12Gx4-lanes

You have only one max bitrate, but there are 6x modes, and it's up to each device manufacturer which modes it wants to support - and I note that you have the various modes for DisplayPort.

**Comment by tomverbeure** [comment]
Hi Tim,

sorry for the very late reply: I somehow don't get emails about issues that are filed for my GitHub repos, and I didn't notice your's until now.

I've added the additional link rates.

Thanks!
Tom

**Comment by tim292stro** [comment]
No problem, I wasn't expecting much if any response anyway as it was for your benefit.

A critique, the bit rates for HDMI 2.1 FRL are expressed in Gbps.  I wanna verify some data (like FRL packing overhead) as a Idetect some weirdness - but before I go there, where did you get your timing data from?  Latest version is CTA-861-G (2016).

Also, would you be interested in adding or linking a VIC to search a format?

**Comment by tomverbeure** [comment]
The video timings themselves (CVT etc) are reverse engineered from the VESA CVT spreadsheet. They are supposed to be exact.

Whether or not a particular timing fits in a transmission protocol is much more wishy-washy: I simply calculate the theoretical bit rate, correct for 8b10 and 16b18 encoding, and check if it fits.  In practice, this works pretty well even if you get close to the limit for DP, DVI, and regular HDMI. I don't know enough about HDMI FRL to adjust for packet and framing overhead, so that needs to be taken with a grain of salt.

I'm in the process of adding DMT timing and CTA timings. The biggest problem was getting them into a json format.  I couldn't find exactly what I wanted, so I created them myself by cut-and-pasting-and-manuall-adjusting things from the DMT and CEA pdf files. The raw data is here: https://github.com/tomverbeure/tomverbeure.github.io/tree/cvt/assets/video_timings.

This now needs to be integrated into the timing calculator. That's work in progress...

VIC will be part of this too.

**Comment by tim292stro** [comment]
How do you want the VIC data in JSON?  I can port over CTA-861-G for you and dig out the latest DMT, but I see you have a dump of 861-G already...  I'd kind of recommend that you do an array of mode objects with some standard keys.

Something like:
```
{
   "modes":[
      {
         "Type":"CEA",
         "VIC":1,
         "3D":False,
         "HorizontalActive":640,
         "VerticalActive":480,
         "InterlacedProgressive":"Progressive",
         "HorizontalTotal":800,
         "HorizontalBlank":160,
         "VerticalTotal":525,
         "VerticalBlank":45,
         "HorizontalFrequencykHz":31.468,
         "VerticalFrequencyHz":59.94,
         "PixelFrequencyMHz":25.175
      },
...
    ]
}
```

That way you could eventually sort by any column in your tool (VIC, resolution, pixel rate, etc...), just by reprocessing the data in the structure with a local script (no extra data transfer or server-side load).  Let me know if it would interest you for me to compile something like that - I'd just need to know what conventions you want to circle the wagons around.

As for the FRL rates, I'll read up on the spec and give you some metrics to use.  There is some 18b 10b encoding overhead, but also comma framing characters and superblock checksums.  I should know that stuff off the top of my head by now as I've written an FRL decoder at work, but since I don't it's a good exercise for me to look it up (again).

**Comment by tomverbeure** [comment]
I've spent some time already integrating DMT. It's not fully done yet, but you can see the intermediate result here: https://github.com/tomverbeure/tomverbeure.github.io/commit/f60fa1611a8b71d760f43fcb1a3d7703c3077179. Part of that effort was converting the DMT file into json: https://github.com/tomverbeure/tomverbeure.github.io/blob/f60fa1611a8b71d760f43fcb1a3d7703c3077179/assets/video_timings/dmt_timings.js.

The same must indeed happen for CEA timings.

One problem with CEA timings is that there is no single one-to-one mapping: there are a lot of footnotes in various tables. It's annoying.

My javascript is also very ugly, with global variables etc. And the UI leaves a lot to be desired as well.

**Comment by tim292stro** [comment]
I'll see what I can whip up based on your structure for the DMT dataset for CEA timings.

As for UI, I'm a sucker for HTML5 Boilerplate, JQuery, and JQueryUI widgets, YMMV

**Comment by tomverbeure** [comment]
I just pushed a big update: CEA and DMT timings, Modeline generation, HSYNC/VSYNC polarity.

Tom
